on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run --name buildkit -d --privileged -p 1234:1234 moby/buildkit --addr tcp://0.0.0.0:1234
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
        name: Setup BuildKit
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: buildkit-cache
          key: v1
      - name: Build docker container
        run: python3 .github/workflows/buildkit-wrapper.py | docker load
        env:
          BUILDKIT_HOST: tcp://localhost:1234
      - name: Upload docker image
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          ./ci-files/cat-env.py DOCKERHUB_TOKEN | docker login --username rinsuki --password-stdin
          docker push rinsuki/discord-who-is-that-pokemon:latest
          docker logout
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
